version: '3.8'

services:
  backend:
    image: your_backend_image
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_DEV_PORT}:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - APP_URL=${APP_URL}
    depends_on:
      - db
    networks:
      - backend-net

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - backend-net

  frontend:
    image: your_frontend_image
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend-net
    depends_on:
      - backend

networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge

volumes:
  db-data:
